### ISSUE TITLE
Change in format of data and log volumes

### ISSUE THREAD

**Issue by balahari18** [NetAppDocs/bluexp-backup-recovery#121]
Page: [Back up cloud-native Oracle databases](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-cloud-native-oracle-data.html)
SC_PRIMARY_DATA_VOLUME_FULL_PATH and SC_PRIMARY_ARCHIVELOGS_VOLUME_FULL_PATH has format mentioned as /{anfaccount}/{subscription_id}/{resource_group}/{capacity_pool}/{volumename}

Request format change in both these params as below /subscriptions/{subscription_id}/resourceGroups/{resource_group}/providers/{provider}/netAppAccounts/{anfaccount}/capacityPools/{capacity_pool}/volumes/{volumename}

**Comment by netapp-soumikd** [comment]
@balahari18 I have fixed your comment. You can verify here: https://review.docs.netapp.com/us-en/bluexp-backup-recovery_bluexp25_releasebranch/task-backup-cloud-native-oracle-data.html#create-policy-to-protect-oracle-database

**Comment by balahari18** [comment]
Verified and approved

**Comment by netapp-soumikd** [comment]
Thanks for verifying.
