### ISSUE TITLE
Admin credentials to be used in registration of the SCV appliance needs to be clarified.

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/bluexp-backup-recovery#124]
### Page URL

https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-register-snapCenter-plug-in-for-vmware-vsphere.html

### Page title

Register SnapCenter Plug-in for VMware vSphere host

### Summary

The user account/password to be used needs to be clarified to be the vCenter administrator account & password.  Currently item 4.c reads:

In the Username and Password field, specify the credentials of the user with the administrator role.

This should be updated to:
In the Username and Password field, specify the credentials of the vCenter user with the administrator role.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manishc** [comment]
Hi. Thank you for contacting us with your feedback, I will make this change and publish the documentation.

**Comment by netapp-manishc** [comment]
@DrKeno: I have incorporated the suggested change: https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-register-snapCenter-plug-in-for-vmware-vsphere.html
