### ISSUE TITLE
Terminology update

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-backup-recovery#137]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-vm-data-in-cloud.html

### Page title

Manage protection of datastores and virtual machines data

### Summary

There's an instance of "Cloud Backup" at the end of this page. Please update it to "BlueXP backup and recovery"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-soumikd** [comment]
I have fixed the terminology and the content is now published.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-vm-data-in-cloud.html
