### ISSUE TITLE
The policy that provided by the document is invalid during configure system for a private connection using a VPC endpoint interface

### ISSUE THREAD

**Issue by yanw113** [NetAppDocs/bluexp-backup-recovery#138]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html

### Page title

Back up on-premises ONTAP data to Amazon S3

### Summary

In the below step:

Modify the security group configuration that’s associated with the BlueXP Connector. You must change the policy to "Custom" (from "Full Access"), and you must [add the S3 permissions from the backup policy](https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html#set-up-s3-permissions) as shown earlier.

When clicking the hyper-link  "add the S3 permissions from the backup policy":
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html#set-up-s3-permissions

It will go to here:

![image](https://github.com/NetAppDocs/bluexp-backup-recovery/assets/138418267/1462e761-5c76-45e7-8f8e-93c47f8b4e23)

The JSON is wrong, There's an extra comma at the end

A JSON Validator tool show the below error:

Error: Parse error on line 56:
...etapp-backup-*"	]},
---------------------^
Expecting 'EOF', got ','

But even I remove the comma and try to create the endpoint interface, it still fails with an error like "valid endpoint policy..."

So can you double-check if the configuration steps are correct?

Or do we have to follow the below requirement strictly?

"must change the policy to "Custom" (from "Full Access")"

PS, if i select "full" , creating will succeed 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@yanw113,

Thank you for submitting this feedback. A member of our team will take a look at your feedback and respond soon.

Thanks again,
Ben

**Comment by netapp-tonacki** [comment]
Hi @yanw113, 

My understand is that you do have to change to "Custom".  But I'll check with the Backup team to see what they have to say about that, and about why it's not working when using "Custom".

Thanks for your feedback.   Tom

**Comment by netapp-tonacki** [comment]
Hi @yanw113,

I heard back from the team and they said the following:
"Full Access is not recommended. We have verified the list in the docs with our QA group and it looks to be fine. 
Is there any way we can get the full error he is seeing?"

In your initial email you said it fails with an error like "valid endpoint policy...".  Do you have the full error message?

Thanks, Tom

**Comment by yanw113** [comment]
Sorry for the late reply.

I didn't get further response the customer about the question.

But I have noticed the comma at the end of policy sample has been removed,this at least fixed formatting problems

Thanks a lot
