### ISSUE TITLE
Confusion on if backing up a system with both FlexVol and FlexGroups is supported.

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-backup-recovery#139]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html

### Page title

Back up Cloud Volumes ONTAP data to Azure Blob storage

### Summary

Under "Select the volumes that you want to back up" it states:

Choose the volumes you want to protect. You can choose to protect FlexVol or FlexGroup volumes; however, you cannot select a mix of these for the working environment you chose to protect.

This seems to imply that backing up a system with FlexVol and FlexGroup volumes can't be done.  It should state something about the fact that at creation time, the policy can only protect a FlexVol or FlexGroup.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
@jasonfiset, Thanks for your feedback.  We do need to add more details here.  If a user has FV and FG volumes we need to mention that they can later select a volume from that same working environment and apply a different set of policies; as described here https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#activate-backup-on-additional-volumes-in-a-working-environment

Does that sound good?

**Comment by netapp-tonacki** [comment]
Hi Jason,  I have updated the section for selecting volumes for all the backup topics, for example https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html#select-the-volumes-that-you-want-to-back-up

Let me know if this clarifies how to select different types of volumes.

Thanks, Tom
