### ISSUE TITLE
What Account ID for Private Mode?

### ISSUE THREAD

**Issue by elcunyado** [NetAppDocs/bluexp-backup-recovery#141]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html

### Page title

Set up licensing for BlueXP backup and recovery

### Summary

Hey team,

Hope you are well!  This is John DeMasi, CSA (jdemasi@netapp.com).  I noticed on this page it tells customers they need to download license files to install on Private Mode.  However, when you go to download these files in the Support Site, it requests an Account ID value.  Private Mode customers don't have access to this.  What value should they use?

Thanks!
John

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi John,  Thanks for your feedback.  I did not know the Account ID was not available when deployed in Private mode.  I'll check with the team to see what they have to say about this.  

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi John,  The team told me that you need to use "account-DARKSITE1" as the Account ID.

I will add this to the docs if applicable - I'm just double-checking with the team if we should broadcast this ID in the docs.

Thanks, Tom

**Comment by elcunyado** [comment]
Hey Tom,

Awesome, thank you so much for your help with this!  Have a great day.

Best,
John

**Comment by netapp-tonacki** [comment]
Hi John,  I'm going to close this out now.  Thanks, again.

Tom
