### ISSUE TITLE
Update S3 Storage Classes

### ISSUE THREAD

**Issue by jsbaskerville** [NetAppDocs/bluexp-backup-recovery#147]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-aws-backup-tiers.html

### Page title

AWS S3 archival storage classes and restore retrieval times

### Summary

I am investigating the use of the new storage class:

S3 Intelligent - Tiering * - Optional asynchronous Archive Access tiers 
Archive Access Tier, All Storage / Month | $0.0036 per GB
Deep Archive Access Tier, All Storage / Month | $0.00099 per GB

Is this a valid class of storage for BlueXP Tiering? if so will you refresh the document accordingly.
/Steve

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi Steve,  I am going to close this issue now.  If this storage class is qualified in the future I'll update the docs.

Thanks, Tom
