### ISSUE TITLE
Support for Cloud Volumes ONTAP with private mode?

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-backup-recovery#148]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html

### Page title

Plan your protection journey

### Summary

The last section on this page titled "Support for sites with no internet connectivity" doesn't list support for backing up Cloud Volumes ONTAP. But a release note entry from 9 March 2023 states the following:

> Ability to back up data from Cloud Volumes ONTAP systems in dark sites
> 
> Now you can back up data from Cloud Volumes ONTAP systems installed in AWS and Azure commercial regions to Amazon S3 or Azure Blob. This requires that you install the Connector on a Linux host in the commercial region, and that you deploy the Cloud Volumes ONTAP system there as well. See [Backing up Cloud Volumes ONTAP data to Amazon S3](https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html) and [Backing up Cloud Volumes ONTAP data to Azure Blob](https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html).

So if backing up Cloud Volumes ONTAP to Amazon S3 or Azure Blob is supported, then this page should reflect that.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hey Ben,  I think the March release note entry should change "dark site" to "restricted mode".  That's what we support for Backups with CVOs.  Thanks for catching this.

Tom

**Comment by netapp-tonacki** [comment]
Hi,  I have updated the March release note entry to mention restricted mode instead of dark site.  I think April is when the new deployment modes were announced...
