### ISSUE TITLE
Unclear recommendation about requirement for PAYGO license alongside BYOL license

### ISSUE THREAD

**Issue by finnian345** [NetAppDocs/bluexp-backup-recovery#151]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html

### Page title

Set up licensing for BlueXP backup and recovery

### Summary

There are a few issues in this document. The fundamental issue is that it is required for a user who uses a BYOL license to also have an Azure PAYGO license, due to needing run-off if they use more than the BYOL capacity. Configuration fails without the Azure subscription. 

Under heading "Use a BlueXP backup and recovery PAYGO subscription", you see the line:
 _You should subscribe even if you have a free trial or if you bring your own license (BYOL)_
This "should" should be changed to "must", as it is a requirement when using BYOL, not a recommendation. The writer may speak a dialect of English where this is different. 

Next, under "Use a BlueXP backup and recovery BYOL license", it should be noted somewhere that an Azure MarketPlace subscription is also required, and this line: 
_If the account you are using doesn’t have a marketplace account, the backup service continues to run, but you will continue to see the warnings._
Should note that this is only for onprem backups.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi Finnian,  Thanks for your feedback.  I had heard this may be required at some point, but I did not know it had gone into affect already.  Let me just double-check with the team about the different scenarios and then we'll update the docs.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Finnian,  I heard back from Jacob, the Product Manager, and he said "Actually, its not required, we mandate either PAYGO or BYOL , But we recommend having a PAYGO because if the BYOL expires, it will switch on to PAYGO."

So if you are seeing something different with this specific setup using Azure, I think this might be a bug.

Tom

**Comment by finnian345** [comment]
Hi Tom,

Thank you for the follow up, it looks like you're right in that it's not
required. In the end my customer didn't have a specific endpoint open, but
myself and my escalation engineer thought the Paygo was required on top of
the BYOL.

It looks like no changes needed to the docs. Thanks.

Finnian O'Neill.

**Comment by netapp-tonacki** [comment]
ok, thanks for confirming Finnian.  Closing this issue now.

Tom
