### ISSUE TITLE
Ports listed are incorrect

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/bluexp-backup-recovery#152]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html

### Page title

Back up Cloud Volumes ONTAP data to Azure Blob storage

### Summary

This section:

The instance’s security group must include the required inbound and outbound rules: specifically, rules for ICMP and ports 11104 and 11105. These rules are included in the predefined security group.

- This is relevant for SnapMirror replication but NOT for replication to Object stores (like Azure Blob).  Object transfers are typical GETs and PUTs that occur over https using port 443

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi Brandon,  Thanks for reporting this.  We'll work on clarifying that section to let users know that these Replication requirements are necessary only if they plan to to make replicated copies of their volumes. - not required if they are only making backups to cloud.

I was looking at the other Backup topics for on-prem ONTAP systems and for those we have a requirements section for object storage, and for replicating volumes, which I think makes it clearer.  I'll see if we can make that distinction for the 3 CVO backup topics as well.

Tom

**Comment by netapp-tonacki** [comment]
In the section "Verify ONTAP networking requirements for replicating volumes" for all the Backup topics, I have revised the first sentence to "If you plan to create replicated volumes on a secondary ONTAP system using BlueXP backup and recovery, ensure that the source and destination systems meet following networking requirements." so users know these requirements are only needed if they plan to create replicated volumes on another ONTAP system.  For example, https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html#verify-ontap-networking-requirements-for-replicating-volumes

Let me know what you think.
