### ISSUE TITLE
Explanation of the Size column

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-backup-recovery#153]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html

### Page title

Restore ONTAP data from backup files

### Summary

There isn't an explanation of what the Size Column is showing.  I have an example where a snapshot is consuming 400KB on disk on a on-prem ONTAP system but the size shows 230MB.  What is this size that is shown?  Is this the size of the snapshot without storage efficiencies?  How is this value computed?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi jasonfiset,  It is the size of the Snapshot copy if it says "Local" in the Location column.  Is that the screenshot/page you are looking at?  I compared what appears in that page to what appears in the System Manager (Advanced View) page and the Snapshot is exactly the same size in both places.  Let me know exactly which screen you are looking at, or attach a screenshot in case I am looking in a different place.

Thanks, Tom

**Comment by jasonfiset** [comment]
In my case, I’m working with a customer and the size column does not match the output when we look at the snapshot show command output on the source system.  The source will show ~264KB but the backup stored in Object Storage is 10GiB.


Jason Fiset
Technical Solution Specialist

NetApp
778.997.3470 Mobile Phone
***@***.******@***.***>



From: Tom Onacki ***@***.***>
Date: Tuesday, October 10, 2023 at 11:06 AM
To: NetAppDocs/bluexp-backup-recovery ***@***.***>
Cc: Fiset, Jason ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/bluexp-backup-recovery] Explanation of the Size column (Issue #153)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi jasonfiset, It is the size of the Snapshot copy if it says "Local" in the Location column. Is that the screenshot/page you are looking at? I compared what appears in that page to what appears in the System Manager (Advanced View) page and the Snapshot is exactly the same size in both places. Let me know exactly which screen you are looking at, or attach a screenshot in case I am looking in a different place.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Jason,  I'm still not sure which screen you are referring to.  In the 2 screens below from the Restore wizard - the first screen shows the size of the Local Snapshot and the size of the Cloud Backup.  (I am not actually sure why they are different and I have sent mail to find out).

![image](https://github.com/NetAppDocs/bluexp-backup-recovery/assets/38222299/2ffb5e65-5620-427c-b9ae-e9531bad3ae7)

The 2nd screen is showing the provisioned size of the original volume (not the "used" size").  The newly restored volume will provision the 10 GiB, but only use the size of the snapshot...

Does that help?

**Comment by jasonfiset** [comment]
Here’s the issue I have.  Here’s a CBS backup and the data size says 10.5GiB:

[A screenshot of a computer  Description automatically generated]


When I look at the ONTAP CLI, I see the following:

[A screenshot of a computer  Description automatically generated]

The same snapshot – BXP reports 10.5G, ONTAP reports 300KB.  How is BXP coming up with the size of the snapshot of 10.5G?

Thanks.


Jason Fiset
Technical Solution Specialist

NetApp
778.997.3470 Mobile Phone
***@***.******@***.***>

[signature_3831903481]<https://insight.netapp.com/>

[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>


From: Tom Onacki ***@***.***>
Date: Wednesday, October 11, 2023 at 8:48 AM
To: NetAppDocs/bluexp-backup-recovery ***@***.***>
Cc: Fiset, Jason ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/bluexp-backup-recovery] Explanation of the Size column (Issue #153)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Jason, I'm still not sure which screen you are referring to. In the 2 screens below from the Restore wizard - the first screen shows the size of the Local Snapshot and the size of the Cloud Backup. (I am not actually sure why they are different and I have sent mail to find out).

[image]<https://user-images.githubusercontent.com/38222299/274337612-2ffb5e65-5620-427c-b9ae-e9531bad3ae7.png>

The 2nd screen is showing the provisioned size of the original volume (not the "used" size"). The newly restored volume will provision the 10 GiB, but only use the size of the snapshot...

Does that help?

**Comment by netapp-tonacki** [comment]
Hi Jason,  I have been told that this issue was fixed in the Backup release that went out on Dec 15.  Thanks for bringing it up.

I can forward you the internal Jira thru email if you'd like.  And if you have any further questions or issues about how the size is displayed you can reply to the folks on that Jira.

Thanks, Tom
