### ISSUE TITLE
Restore limitations when restoring files to destination volumes in a snap mirror relationship

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-backup-recovery#155]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html

### Page title

Restore ONTAP data from backup files

### Summary

There's a limitation when restoring files.  If you backup a DP volume and then decide to break the SnapMirror to that volume, you still can't restore files to that volume unless you also delete the SnapMirror relationship or reverse the SnapMirror direction.  This isn't mentioned in the documentation that I could find but is important to highlight.  Restoring to the volume which is the source for a SnapMirror relationship does work just not the destination, even if the volume is in RW mode.  It would be good to explain why this can't be done in the documentation so customers are aware and maybe re-think if they should backup the DP volume or backup from the source system to make restores more intuitive.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Thank you for your comment. We've sent the comment to the Product Manager for clarification and will update the documentation based on the response. Meanwhile, please continue to provide feedback!

**Comment by amgrissino** [comment]
Thank you for your comment. We've sent your question to the Product Manager and will update the document based on the information we get back. Meanwhile, feel free to provide additional feedback!

**Comment by amgrissino** [comment]
Bringing this up again with Product Manager. Hope we can close this.
