### ISSUE TITLE
Cloud Backup Syntax Issue for IAM Setup

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-backup-recovery#158]
### Summary

Found a syntax error with the following instructions for “Set up S3 permissions” in the JSON code provided in Step 2 -> Details. 

[https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html#set-up-s3-permissions](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fbluexp-backup-recovery%2Ftask-backup-onprem-to-aws.html%23set-up-s3-permissions&data=05%7C01%7CChanda.Jha%40netapp.com%7C01fff65ebad9448fe98008dbd5c7d22b%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638338826435291798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M75QGdsMRjKPhvGGnfUDfofjBdQxmJ5Pb9ohbZQb0Ys%3D&reserved=0)

As you can see in the JSON code below we have what seems to be two versions and no guidance on which should be selected.

{
    **"Version": "2012-10-17",
     "Statement": [**
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        }
    ]
}
{
    **"Version": "2012-10-17",
    "Statement": [**
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
@netapp-chandaj  - Thank you for bringing this up. Tom and I will research with Engineering and Product Management and get back to you.

**Comment by amgrissino** [comment]
We've emailed the PM and cc'd you.

**Comment by ksohailshabir** [comment]
@amgrissino @netapp-chandaj Wanted to follow up and see if there is any progress/resolution on this JSON code

**Comment by netapp-tonacki** [comment]
We got verification from the PM and I've updated the JSON statement today.  This is closed now.
