### ISSUE TITLE
Additional notes need for setting up backups in AWS GovCloud Regions

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-backup-recovery#164]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html

### Page title

Back up on-premises ONTAP data to Amazon S3

### Summary

On the "Set up S3 permissions" section of this page, when you expand the details of step 1, you see the following note:

<img width="996" alt="image" src="https://github.com/NetAppDocs/bluexp-backup-recovery/assets/33675510/382c54ac-baf1-4e36-86df-d72bacd2e5f8">

An additional note should be added here with the same type of instructions when AWS GovCloud regions are used, as opposed to China regions.  Suggested wording is:

`When creating backups in AWS GovCloud regions, you need to change the AWS Resource Name "arn" under all Resource sections in the IAM policies from "aws" to "aws-us-gov"; for example arn:aws-us-gov:s3:::netapp-backup-*.`

Additionally, under the details of step 2 and under the details of "Create your own buckets" this note is missing (for both the China regions as well as the AWS GovCloud regions) and should be noted in each of those sections.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Thanks [mimitche](https://github.com/mimitche).  That a good catch.  It's also in the topic for backing up CVO to AWS S3.  We'll get that updated shortly.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
I have made these updates to the Backup Onprem and Backup CVO topics.  Let me know how this looks.

Thanks, Tom

**Comment by mimitche** [comment]
Updates look great- thanks!
