### ISSUE TITLE
Clarify steps for Configure your system for a private connection using a VPC endpoint interface

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-backup-recovery#165]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html

### Page title

Back up on-premises ONTAP data to Amazon S3

### Summary

Step 2 of the "Clarify steps for Configure your system for a private connection using a VPC endpoint interface" section on this page discusses modifying a security group configuration:

<img width="1024" alt="image" src="https://github.com/NetAppDocs/bluexp-backup-recovery/assets/33675510/5c9d8008-66b2-4b83-a979-ebd86af3e1f7">

We are unable to find any matching settings within AWS where a policy is configured directly on a security group.  The screen shot looks most similar to setting a policy on a private endpoint, but still isn't a direct match.

Need this step clarified, or removed if it is determined to not be applicable.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by mimitche** [comment]
Issue 68 definitely lines up with what I am seeing as well.  I'm pretty sure this step can be eliminated altogether.  I have successfully setup Cloud Backup with private connections using these instructions, but just skipped step 2 and it worked fine.

**Comment by netapp-tonacki** [comment]
Thanks Mike,  I think that aligns with what Richard was saying as well.  So if the configuration worked for you when leaving out step 2, than I'll do that today.

Thanks, Tom.

**Comment by netapp-tonacki** [comment]
I have removed old step 2 from that procedure. The docs are updated.  Thanks for the info Mike.
