### ISSUE TITLE
Hyperlink fix for diagrams

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-backup-recovery#166]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html

### Page title

Back up on-premises ONTAP data to Amazon S3

### Summary

In the "Configure your system for a private connection using a VPC endpoint interface" section of this page there are two hyperlinks that reference diagrams published earlier in this page:

<img width="1023" alt="image" src="https://github.com/NetAppDocs/bluexp-backup-recovery/assets/33675510/16aefede-45d0-4911-982b-5bdc6807d226">

Both the "first diagram" and "second diagram" hyperlinks no longer appear to function.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi Mike,  Thanks for catching that too.  I'll make this change, and your previous change, later today.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
I have fixed these 2 broken hyperlinks.  Thanks again.
