### ISSUE TITLE
Clarify instructions in "Create your own buckets" section

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-backup-recovery#169]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html

### Page title

Back up on-premises ONTAP data to Amazon S3

### Summary

On this page, under the "Create your own buckets" section currently looks like this:

<img width="979" alt="image" src="https://github.com/NetAppDocs/bluexp-backup-recovery/assets/33675510/7cb922a8-1c0e-42b8-8cdf-59cc57e90fae">

1.  Change `you should use a bucket name of "netapp-backup"`  to `you should use a bucket name starting with "netapp-backup-" `  (There clarifies that "netapp-backup" is a default prefix and not the entire name to be used for a bucket)
2.  The second sentence here mentions a specific policy used by CVO, but this section is for on-prem ONTAP systems. I suggest updating to `If you need to use a custom bucket name, edit the policies used in the "Setup S3 permissions" section to use a Resource ARN that matches your custom bucket name prefix.`

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Thanks for the comment Mike.  That section does need to get cleaned up and those are great suggestions.  

Tom

**Comment by amgrissino** [comment]
Will add this update to the updates this morning. Thank you, Mike.

**Comment by amgrissino** [comment]
Docs are updated with your feedback. Thank you! https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html#create-your-own-buckets

**Comment by amgrissino** [comment]
Closing
