### ISSUE TITLE
Incorrect link in DataLock and Ransomware protection options section

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-backup-recovery#177]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html

### Page title

Backup-to-object policy options

### Summary

The hyperlink for this sentence is incorrect:  Refer to [How to update Ransomware protection options in the Advanced Settings page](https://docs.netapp.com/us-en/bluexp-backup-recovery/manage-backup-settings-ontap.html).

The hyperlink should be pointing to this: https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html

it is missing the "-task" after the last "/" in the current hyperlink.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Thanks David for catching that.  We have a minor doc update scheduled for today, so we'll get that done very soon.

Thanks, Tom

**Comment by virtualhawk** [comment]
Thanks Tom!  I appreciate it!

Thanks,

David Hawkins
Professional Service Consultant
Global Services Solutions Center

NetApp
330.892.7057 Direct Phone
***@***.******@***.***>

[A logo with a white square on it    Description automatically generated with medium confidence]

[A black circle with white letters    Description automatically generated]   [A black and white logo    Description automatically generated]    [A black and white logo    Description automatically generated]    [A black circle with a white play button    Description automatically generated]    [A black circle with white letters in it    Description automatically generated]    [A black circle with white x in it    Description automatically generated]    [A black circle with white logo    Description automatically generated]

"We're committed to providing our customers with the best products and services. Scan the QR code or click on this link<https://listening.netapp.com/jfe/form/SV_3n6lnfKz33d6feC> to provide your feedback. All responses will be anonymous and kept confidential.  Thank you!"

**Comment by amgrissino** [comment]
Pushed a minor update out just now and included this link fix. Thank you, David! 
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection-options-2

**Comment by amgrissino** [comment]
Closing this
