### ISSUE TITLE
Improve "Podman" explanation

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/bluexp-backup-recovery#180]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html

### Page title

Known limitations

### Summary

Hi, this addition is great!

I was concern that a BlueXP Backup & Recovery reader may not understand or be aware of what is the meaning of Podman in this context and the context should be better added.

Something easy could be enough:
Now -> "restore is not supported when using Podman"
Proposed -> "restore is not supported when using BlueXP Connectors running in Podman (manually created BlueXP Connectors running on RHEL 8 or 9)"

Or, maybe just add a link reference text like Podman ([details](https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-operating-system-changes.html)).

Regards,
Gabriel

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Added some notes to this topic https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html#limitations-when-using-rhel-8-with-podman.  Pushing out changes in a few minutes.
