### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-backup-recovery#192]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html

### Page title

Monitor the status of backup and restore jobs

### Summary

"BlueXP backup and recovery replication **brake** job failure"

should be

"BlueXP backup and recovery replication **break** job failure"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Publishing fix now.
