### ISSUE TITLE
Changes to buffer period and minimum RUD

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/bluexp-backup-recovery#193]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html

### Page title

Backup-to-object policy options

### Summary

The buffer period is described in the "What is DataLock" as 14 days, but this is changing. In ONTAP 9.12.1P13, 9.13.1P10, 9.14.1P5, 9.15.1 and later, the buffer period is going to be 31 days.

We need a note or update to ensure customers and the field are aware of this change. My thought was having a "note" / "!" section after the last bullet in the "What is DataLock" section similar to:
"
In ONTAP 9.12.1P13, 9.13.1P10, 9.14.1P5, 9.15.1, and later, the buffer period is increased from 14 days to 31 days. This results in an additional 31 days applied to all new retention calculations and makes the new minimum retention 61 days.
"

Feel free to suggest another way to word this, or list the ONTAP versions.
I think eventually we need to update the whole section to stop referencing the old 14 day buffer period, but this should work while it's dependent on a customer's ONTAP version.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
@netapp-joey - Thank you for your comment. I've reached out to the Product Manager to confirm. After I get a confirmation, I'll update the page and let you know. Meanwhile, if you see anything else that needs an update, let us know. Thanks again!

**Comment by amgrissino** [comment]
We've contacted Eng. Will let you know.

**Comment by amgrissino** [comment]
@netapp-joey. We've gotten feedback from PM and Eng: DataLock protects your backup files from being modified or deleted for a certain period of time - also called immutable storage. This functionality uses technology from the object storage provider for "object locking." The period of time that the backup file is locked (and retained) is called the DataLock Retention Period. It is based on the backup policy schedule and retention setting that you defined; plus a max of 31-days  buffer. Any DataLock retention policy that is less than 31 days is rounded up to 31 days minimum.

**Comment by amgrissino** [comment]
Will be updating the docs today.

**Comment by amgrissino** [comment]
Closing this. Docs updated.
