### ISSUE TITLE
Update docs to reflect that Datalock cannot be enabled later

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-backup-recovery#197]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html

### Page title

Backup-to-object policy options

### Summary

Currently this page states the following:

```
If you plan to use DataLock and Ransomware protection, you can enable it when creating your first backup policy and activating BlueXP backup and recovery for that cluster. You can later enable it using BlueXP backup and recovery Advanced Settings.

DataLock and Ransomware protection can be disabled for a cluster after it has been configured to save costs.
```

While ransomware scanning can be enabled or disabled later in the Advanced Settings section, Datalock cannot be enabled after backups are activated for a working environment.

Similarly, Datalock cannot be disabled after being enabled for a working environment.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
@mimitche - You can later disable Ransomware scan [Not Datalock ] in the advance setting page. Will change this.

**Comment by mimitche** [comment]
That's true about disabling Ransomware scanning; however you still can't change Datalock after the fact, so the following:

`You can later enable it using BlueXP backup and recovery Advanced Settings.`

Is still wrong.

**Comment by amgrissino** [comment]
Yes, that is being removed now.

**Comment by amgrissino** [comment]
Updates are live here: https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#what-is-datalock

**Comment by amgrissino** [comment]
@mimitche Thank you for your review. If you see anything else that needs an update, don't hesitate to let us know. Closing this.
