### ISSUE TITLE
Clarify Bulk Operations for enabling backups on multiple volumes will only initialize volumes in batches of 5.

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-backup-recovery#202]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html

### Page title

Manage backups for your ONTAP systems

### Summary

In the "Edit backup settings on multiple volumes" of this page, a note needs to be added about what happens when more than 5 volumes are enabled for backup at a time via Bulk Operations.

When more than 5 volumes are enabled for backup, BlueXP Backup & Recovery only initializes 5 volumes at a time.  When those initializations are finished, it creates the next batch of 5 subjobs to initialize volumes, and continues until all volumes are  initialized.  This is not documented anywhere and causes confusion for backup admins as it appears that the additional volumes they selected are being ignored.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
@mimitche Thank you for your feedback. I'm returning from being OOO. Apologize for delay in responding. I've sent your comment to the Product Manager.

**Comment by amgrissino** [comment]
Updated topic. Closing.
