### ISSUE TITLE
Correct supported backup sources for restricted mode

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-backup-recovery#204]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html

### Page title

Plan your protection journey

### Summary

In the section titled "Support for sites with limited internet connectivity" on this page, it implies that backup to AWS S3 or Azure Blob is only supported from CVO instances for restricted mode:

<img width="995" alt="image" src="https://github.com/user-attachments/assets/7c8e88ca-d98f-4a48-ac3a-27fb8a9b1e32">

This is incorrect, as an on-prem ONTAP cluster is also supported for backup to AWS S3 or Azure Blob in restricted mode, including when AWS S3 or Azure Blob is in a government region.  This has been tested and confirmed as supported by Jacob JA.

Suggest the following update:

> BlueXP backup and recovery can be used in a site with limited internet connectivity (also known as restricted mode) to back up volume data. In this case, you'll need to deploy the BlueXP Connector in the _destination cloud region_.
> 
> You can back up data from _on-premises ONTAP systems or Cloud Volumes ONTAP systems installed in AWS commercial or government regions to Amazon S3_. [Back up Cloud Volumes ONTAP data to Amazon S3](https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html).
> 
> You can back up data from _on-premises ONTAP systems or Cloud Volumes ONTAP systems installed in Azure commercial or government regions to Azure Blob_. [Back up Cloud Volumes ONTAP data to Azure Blob](https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Thank you, @mimitche. Great that it has been tested and confirmed by Jacob JA. Thanks for that info. Will confirm with team and hope to get back to you quickly.

**Comment by amgrissino** [comment]
Updated the topic. Closing.
