### ISSUE TITLE
Podman restart commands wrong

### ISSUE THREAD

**Issue by alexmal98** [NetAppDocs/bluexp-backup-recovery#205]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html

### Page title

Restart the BlueXP backup and recovery service

### Summary

The podman restart commands are wrong.  I'm not sure why the ' is at the end of the commands.  I had a customer struggle with restarting the service and they were able to determine that podman restart cloudmanager_cbs works.  Please update the table.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Updated. Closing.
