### ISSUE TITLE
S3 permissions should be mentioned on this page

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-backup-recovery#209]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html

### Page title

Back up on-premises ONTAP data to StorageGRID

### Summary

The StorageGRID S3 permissions listed in this section:
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#requirements

Should be referenced in the following section as a requirement to prepare StorageGRID:
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#prepare-storagegrid-as-your-backup-target

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
This comment was provided by NetApp support.

**Comment by amgrissino** [comment]
Thank you, @netapp-bcammett, for your comment. Pushing that update out today.
