### ISSUE TITLE
Create your Azure Blob storage account - container to be created manually

### ISSUE THREAD

**Issue by e175006** [NetAppDocs/bluexp-backup-recovery#212]
### Page URL

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-azure.html

### Page title

Back up on-premises ONTAP data to Azure Blob storage

### Summary

Hello,
I believe the document is not correctly mentions how the container should be created within the storage account.
Under the "Create your Azure Blob storage account" I believe you need to mention that for a usage of pre-created storage accounts you MUST take care of the container creation manually otherwise BlueXP will faile to communicate to a container.
This article describes the issue:
https://kb.netapp.com/Cloud/BlueXP/Cloud_Backup_Service/Unable_to_configure_BlueXP_volume_backup_when_selecting_Bring_Your_Own_Storage_Account
So I think it would be beneficial to put it part of the procedure.

Here it is mentioned that you MAY create your own Container, instead it should be "MUST".
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container
Also perhaps its worth mentioning that the container name to be identical to the storage account???

Regards.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Thank you @e175006 for your feedback. We're checking with the product team. Meanwhile, if you see anything else, don't hesitate to let us know.

**Comment by amgrissino** [comment]
Discussed this with the product team. We will update the BlueXP backup and recovery documentation with the info that you cited. Thank you! Will let you know when this is done.

**Comment by amgrissino** [comment]
See if this draft topic in a staging branch does the trick: https://review.docs.netapp.com/us-en/bluexp-backup-recovery_br-gh-sg/task-backup-onprem-to-azure.html#create-your-azure-blob-storage-account  and here: https://review.docs.netapp.com/us-en/bluexp-backup-recovery_br-gh-sg/task-backup-onprem-to-azure.html#define-the-backup-strategy

You'll VPN to access the staging site.

**Comment by amgrissino** [comment]
See if this info does the trick (in 2 places): 

![image](https://github.com/user-attachments/assets/07a1bee5-b36b-4886-8e07-59fd3ab5abdd)

**Comment by amgrissino** [comment]
@e175006 Also here: 
![image](https://github.com/user-attachments/assets/ae813c8a-61b7-46e8-86fd-356210bdb0bb)

**Comment by amgrissino** [comment]
Also here: 

Do you want to create your own object storage container

When you create backup files in object storage for a working environment, by default, the backup and recovery service creates the container (bucket or storage account) for the backup files in the object storage account that you have configured. The AWS or GCP bucket is named "netapp-backup-<uuid>" by default. The Azure Blob storage account is named "netappbackup<uuid>".

You can create the container yourself in the object provider account if you want to use a certain prefix or assign special properties. If you want to create your own container, you must create it before starting the activation wizard. BlueXP backup and recovery can use any bucket and share buckets. The backup activation wizard will automatically discover your provisioned containers for the selected Account and credentials so that you can select the one you want to use.

If you want to use your own storage accounts, create them before you start the backup activation wizard and then select those storage accounts in the wizard. Manually create a container inside the Azure Blob storage account using the Azure portal. For BlueXP to use it, the new container must have the same name as the storage account.

**Comment by e175006** [comment]
Hi Ann-Marie,
Thank you for addressing this issue. I reviewed the corrected pictures, and they look good. You may close the thread.

In our case, this matches the requirement. However, for clarity, you mentioned:

“When you create backup files in object storage for a working environment, by default, the backup and recovery service creates the container (bucket or storage account) for the backup files in the object storage account that you have configured. The AWS or GCP bucket is named 'netapp-backup-' by default. The Azure Blob storage account is named 'netappbackup'."

What do you mean by “working environment”?

We have some on-premises clusters with volumes full of data that we wanted to back up through CBS. We followed the documentation to enable this from BlueXP, selected the “Bring your own account” option, and marked the storage account that had been manually deployed in advance. However, it kept failing to create the container “netappbackup,” stating that the connection with the container could not be established.

As a result, we manually created a container with the name of the storage account. Given that the BlueXP connector had all necessary Azure IAM permissions to create containers, I would expect BlueXP to handle this task.

If any manual steps (like container creation) can be avoided, I would prefer BlueXP to do it.

Hopefully, this can be addressed in future versions.Thanks a lot.

Regards.
--
Sergey Cherny
Cloud Architect
Global Information Services
***@***.******@***.***>
www.appliedmaterials.com<http://www.appliedmaterials.com>


The content of this message is APPLIED MATERIALS CONFIDENTIAL. If you are not the intended recipient, please notify me, delete this email and do not use or distribute this email.

From: Ann-Marie Grissino ***@***.***>
Sent: Tuesday, November 26, 2024 11:35 PM
To: NetAppDocs/bluexp-backup-recovery ***@***.***>
Cc: Sergey Cherny ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NetAppDocs/bluexp-backup-recovery] Create your Azure Blob storage account - container to be created manually (Issue #212)

Also here: Do you want to create your own object storage container When you create backup files in object storage for a working environment, by default, the backup and recovery service creates the container (bucket or storage account) for the


Also here:

Do you want to create your own object storage container

When you create backup files in object storage for a working environment, by default, the backup and recovery service creates the container (bucket or storage account) for the backup files in the object storage account that you have configured. The AWS or GCP bucket is named "netapp-backup-" by default. The Azure Blob storage account is named "netappbackup".

You can create the container yourself in the object provider account if you want to use a certain prefix or assign special properties. If you want to create your own container, you must create it before starting the activation wizard. BlueXP backup and recovery can use any bucket and share buckets. The backup activation wizard will automatically discover your provisioned containers for the selected Account and credentials so that you can select the one you want to use.

If you want to use your own storage accounts, create them before you start the backup activation wizard and then select those storage accounts in the wizard. Manually create a container inside the Azure Blob storage account using the Azure portal. For BlueXP to use it, the new container must have the same name as the storage account.

**Comment by amgrissino** [comment]
@e175006  Very good. I will send your comments to the product team for their awareness and planning. And, will close this thread, as you indicated. 

A working environment represents a storage system. For example:

- A Cloud Volumes ONTAP system
- An on-premises ONTAP cluster
- A StorageGRID system

More info here: https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html#overview

**Comment by amgrissino** [comment]
Closing this. Sent comments to Product Team.
