### ISSUE TITLE
A couple of different issues on backup policy

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/bluexp-backup-recovery#67]
Page: [Backing up on-premises ONTAP data to Amazon S3](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-aws.html)

there is a missing comma on this line:
   "s3:PutBucketOwnershipControls"

AWS says this permission doesn't exist:
"s3:ListBucketByTags",

**Comment by netapp-tonacki** [comment]
Hi Richard,   Thanks for your comments.

I have added a comma to fix the first issue.  Should go live in the next day.

For the other item.  I can find this permission in the https://docs.aws.amazon.com/whitepapers/latest/migrate-apache-hbase-s3/appendix-b-aws-iam-policy-reference.html .  And we still have it in our Connector docs here https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-aws.html#cloud-backup.  So I'm not sure what the resolution is.  Do you get an error or something when you use it?

Thanks, Tom

**Comment by nichollri** [comment]
I was on with a customer and when assigning this permission the AWS console complained on the " "s3:ListBucketByTags" was not valid.  I will try to duplicate this in my own environment.

**Comment by ntap-bmegan** [comment]
@netapp-tonacki - What is the status of this issue?

**Comment by netapp-tonacki** [comment]
Hi Richard,  I am planning to close this based on my last comment.  Do you have any objection?  Or have you found out that it is really NOT needed from any of your contacts?

Thanks, Tom

**Comment by nichollri** [comment]
Tom I am confused still a bit on this.
I see ListBucket and ListBucketVersion,  but I do NOT see ListBucketByTags in the permissions for a connector that I deploy from BlueXP:

[bluexp-permissions-connector.txt](https://github.com/NetAppDocs/bluexp-backup-recovery/files/12501168/bluexp-permissions-connector.txt)

If I try to add to policy, to AWS I get unknown action:
![image](https://github.com/NetAppDocs/bluexp-backup-recovery/assets/519212/e1ea7e00-0728-46b7-a9f7-cb06b506d1d3)

And I still see this on the CBS page listed as a permission.

![image](https://github.com/NetAppDocs/bluexp-backup-recovery/assets/519212/226a54ba-6b08-401c-a869-7e541ed8de1a)

**Comment by netapp-tonacki** [comment]
Hi Richard.  If it is no longer in the policy when deploying the Connector, then it looks like the team finally removed unneeded items.  Thanks for confirming that it is really no longer needed.   I'll pull it out of the Backup docs now.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi,  I removed the unneeded policy item from 4 places in the the Backup docs.
Thanks again Richard.

Tom
