### ISSUE TITLE
Step #2 is confusing "Modify the security group configuration that’s associated with the BlueXP Connector"

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/bluexp-backup-recovery#68]
Page: [Backing up on-premises ONTAP data to Amazon S3](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-aws.html)

Step #2 is right after you create an endpoint, but then it references the SG attached to the **connector**.
The SG attached to the connector doesn't have policies associated with it.
It just inbound/outbound rules.
The role associated to the connector should have the permissions listed here, but those were already discussed and not sure what that has to do with setting up an endpoint (step #1).

Now Endpoints themselves do have SG and Policies.
So I assume we should be telling the user to make sure that the SG allows port 443 if you are setting up https for the s3 object communication.

I guess you "could" lock down the policy on the "Endpoint" to the permissions listed in the s3 backup policy, but I don't think that is required.  I have full access in my policy in the past and have been able to backup via the vpce interface.

![image](https://user-images.githubusercontent.com/519212/205737360-edd4b09a-845d-4575-a673-33a977290a8c.png)

**Comment by netapp-tonacki** [comment]
Thanks for your comment Richard.   I am trying to locate where I got this info to add in the docs in the first part of this year - I haven't found it yet...   I'll search some more in hopes that clarifies something for me..

**Comment by netapp-tonacki** [comment]
Hey Richard, Another NetApp person entered an issue about this (Issue #165) that corroborated what you were saying.  He said he skipped step 2 and everything worked fine. So I removed that step from the procedure.

Let me know if you have any issue with that or if you have further thoughts about this procedure.  Then I can close this out.

Thanks, Tom

**Comment by nichollri** [comment]
thanks Tom.  Sorry had missed this message.  All good to me.
