### ISSUE TITLE
Documentation references still needing StorageAdmin role

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-backup-recovery#87]
Page: [Backing up Cloud Volumes ONTAP data to Google Cloud Storage](https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-to-gcp.html)

This page references the CVO Service Account still needing the GCP "StorageAdmin" role, but that requirement was removed and replaced with a more limited custom role according to this release note:
https://docs.netapp.com/us-en/cloud-manager-backup-restore/whats-new.html#storage-admin-role-no-longer-needed-for-the-service-account-to-create-backups-in-google-cloud-storage

It does appear the permissions were updated in the "Backup on-premises ONTAP to Google Cloud" section (https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups) but not in this "Backup CVO to Google Cloud" section.

**Comment by netapp-tonacki** [comment]
Hi mimitche,  Good catch.  This was actually done on purpose.  At this time, when you deploy a CVO on GCP it requires the Storage Admin role [https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-creating-gcp-service-account.html].  You can't pick another role.  So there needs to be changes made to the CVO deployment flow to allow a different (custom) role to be selected.  I don't know the status, but I'll check and add what I find out here.

Thanks, Tom

**Comment by amgrissino** [comment]
Hello, @mimitche. I just talked with the Product Manager, Jacob, and he confirmed your note that the Storage Admin role is no longer required and a custom role is good. Will update the Backup to CVO topic. Thank you.

**Comment by amgrissino** [comment]
I spoke with the Product Manager and he confirmed your information that the Storage Admin role is no longer required. 
Will update the Back up CVO to GSP info.

**Comment by amgrissino** [comment]
Topic updated with custom role info. Storage Admin role removed. 

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-gcp.html

Closing this.
